### ISSUE TITLE
Update Requirements

### ISSUE THREAD

**Issue by semihakgul** [bounswe/bounswe2019group11#197]
We have to update requirements according to the feedback on piazza.

**Comment by semihakgul** [comment]
You can see the changes in the requirements and edit them in this document.
https://docs.google.com/document/d/1P-UhEGxgx0K-C9AVVtAg7mmkus1Uc29zq8vBAoIBSSc/edit?usp=sharing

**Comment by hasan-yaman** [comment]
Thank you @semihakgul . You did very well on this.
