### ISSUE TITLE
Author name overlaps with date.

### ISSUE THREAD

**Issue by hasan-yaman** [bounswe/bounswe2019group11#216]
In the article section, in my phone the name of the author overlaps with the date.My deice is Huawei FIG-LX1 that has 5.5 inch screen. You can see the output in the added screenshot.
![Screenshot_20191120_194333_com papel](https://user-images.githubusercontent.com/23437545/69258941-7f971e00-0bce-11ea-8de3-880d379eefff.jpg)

Possible solution can be showing only day and month of the date or something else.

**Comment by aysusayin** [comment]
Hi Hasan,
I fixed the bug in the pr #222. Could you check if the problem is gone in your device?

**Comment by hasan-yaman** [comment]
Thank you Aysu.
I will check and inform you.

**Comment by hasan-yaman** [comment]
It works perfect! 
![Screenshot_20191121_204006_com papel](https://user-images.githubusercontent.com/23437545/69362271-411d6400-0c9f-11ea-984e-445f4df3ae14.jpg)
