### ISSUE TITLE
Create Sequence Diagrams

### ISSUE THREAD

**Issue by MirageOwl** [bounswe/bounswe2019group11#23]
Deadline 17.03.2019 23.59

**Comment by uskudarli** [comment]
Notes: A whole lot more of information as well as discussion would be expected in this thread. For example.

Also, it makes sense to split up the sequence diagrams and assign to individuals. Why? So it can be tracked.

Link to use cases, class diagrams...

In discussion the links to created sequence diagrams, etc.
