### ISSUE TITLE
Implement Comments on Articles

### ISSUE THREAD

**Issue by MirageOwl** [bounswe/bounswe2019group11#232]
- All users need to be able to view comments on articles.
- Registered users need to be able to add new comments to articles.
- Registered users can like and dislike individual comments.

**Comment by semihakgul** [comment]
-  Currently all users can view comments. ✓

-  We have problems on this. I can not manage to send user token. @MirageOwl Can you have a look at it?

**Comment by semihakgul** [comment]
Comments can be added now thanks to @MirageOwl .

**Comment by semihakgul** [comment]
Liking comments will not be implemented.
