### ISSUE TITLE
Revisit mockups

### ISSUE THREAD

**Issue by hasan-yaman** [bounswe/bounswe2019group11#24]

**Comment by hasan-yaman** [comment]
Some feedbacks we should consider:
1. The type of trading equipment should be specific for prediction success ratio (e.g., BIST100 prediction success ratio) in profile pages.
2. In the 2nd page of the last mock-up, Ugur chooses events section. However, economic events should include numeric values. Check https://www.investing.com/economic-calendar/ for more information about economic events. What you refer is a news section, which is not a required requirements by your customer, but if you want to have a "news" section, you are more than welcome to do it.
3. I cannot understand from the mock-up how Ugur sets a sell order for cryptocurrency's price. Also, how are you planning to set a sell order for a percentage change? What will the base price be for the 10 percent change? The price he bought or the price of the last day's close? You should strictly specify it.

**Comment by aysusayin** [comment]
I remade the mockups according to feedback 1 and 2.
