### ISSUE TITLE
Revisit use case

### ISSUE THREAD

**Issue by hasan-yaman** [bounswe/bounswe2019group11#25]
1. In use case diagram, how about registering?
 **We should add registering.**
2. In use case diagram, what you want to refer by sign in is sign up. Instead of "provide location information", write "select location via Google Maps". Also, it should be connected to Guest rather than BasicUser.
3. In use case diagram, how about removing trading equipments (under Portfolio). 
**Add another feature that is "Remove Trading Equipment."** 
4. For use case diagram, check "use case generalization". You may apply it for some parts of your diagram.
**I think we use inheritance but let's research use case generalization.**
5. In use case diagram, you miss some of your requirements. For exaple, how about setting alerts for trading equipments?
**Add setting alerts.**

**Comment by aysusayin** [comment]
Need to update wiki page before closing this issue.

**Comment by hasan-yaman** [comment]
I updated the wiki page.
