### ISSUE TITLE
Bug in adding elements to other profiles' portfolio

### ISSUE THREAD

**Issue by alperen-degirmenci-2017400255** [bounswe/bounswe2019group11#251]
As seen in #250 , portfolios and articles are now available and clickable on pages of other profiles. But, a small bug is as following: 
When you visit those profiles and view other portfolios, user is able to add elements to **others' portfolios.**

**Comment by hasan-yaman** [comment]
I am working on it.

**Comment by hasan-yaman** [comment]
I am not available. @alperen-degirmenci-2017400255  can you look at it?

**Comment by alperen-degirmenci-2017400255** [comment]
Oh, ok. I will fix it immediately.

**Comment by alperen-degirmenci-2017400255** [comment]
Solved by #252 .
