### ISSUE TITLE
update sequence diagrams

### ISSUE THREAD

**Issue by mdumandag** [bounswe/bounswe2019group11#26]
after class diagrams are updated accroding to feedbacks, changes should be reflected to the sequence diagrams.

**Comment by uskudarli** [comment]
Again, the current issues description makes it difficult to track.

You may also benefit from creating a "Project" form the "Projects" link at top of page.

**Comment by semihakgul** [comment]
Sequence diagrams about register, making comment and prediction are renewed depending on the feedbacks, on the disscussions made in the meetings and on the renewed class diagram.

**Comment by semihakgul** [comment]
Addtionally the links to diagrams are below.  Unfortunately I can not provide the register diagram link.
https://www.lucidchart.com/invitations/accept/87fa2bb5-8164-4229-a164-ac163dbd4393
https://www.lucidchart.com/invitations/accept/7f0e0abe-cb2a-4aee-8568-e6a0e2cd0970
