### ISSUE TITLE
update class diagrams

### ISSUE THREAD

**Issue by mdumandag** [bounswe/bounswe2019group11#28]
class diagrams should be updated with respect to the customer feedbacks and required functions and classes that we found while preparing the sequence diagrams should also be added.

Here are my propasals for the new classes and functions.

- There should be a Database class given a query string, performs the query and returns the query results
- sanitizeInput method under the controller class, given a string performs basic input sanitization such as trimming trailing white spaces and returns the sanitized string
- for every method that access database in the registered user class, there should be an equivalent method in the controller class with the same parameters plus the user reference so that the controller can do an access control and prepare a database query and return the query results.

- I also think that classes like comment, article, portfolio should be classes that just store the state (like the represantition of what is in the database). Methods in these classes should be in the user class. I think it doesn't make much sense that a comment can delete itself. How can we do an access control in that case ?

**Comment by alperen-degirmenci-2017400255** [comment]
Sanitize Input method added.

**Comment by uskudarli** [comment]
you need assignees right?

**Comment by alperen-degirmenci-2017400255** [comment]
Updated the controller class, moved some functions from **comment** and **article** to user class.

**Comment by semihakgul** [comment]
After the updates done by Alperen and Cumhur, Database class is added to the class diagram by Metin. I also made minor changes. I am sharing the link of the class diagram, which was previously shared via WhatsApp...
https://www.lucidchart.com/invitations/accept/cf91c21a-aa72-4037-9832-44182ddafcd2
