### ISSUE TITLE
Implement investments page for Android

### ISSUE THREAD

**Issue by aysusayin** [bounswe/bounswe2019group11#306]
Implement investments page for mobile. There shall be a page for listing all the investments of the user and a part for adding new investments. See requirements 1.1.2.1, 1.1.3.1, 1.1.3.3 and 1.2.3.

**Comment by aysusayin** [comment]
The investments page needs to be updated as follows: 
- [] The add  button should direct user to a new activity where user can select (and search) trading equipment and get the amount. 
- [] There shall be a sell button next to each trading equipment.

**Comment by hasan-yaman** [comment]
Solved by #379
