### ISSUE TITLE
Preparing the report on Milestone1 

### ISSUE THREAD

**Issue by alperen-degirmenci-2017400255** [bounswe/bounswe2019group11#33]
This task includes collecting the content created for the Milestone1 report from group members and preparing the PDF file with the content.

**Comment by alperen-degirmenci-2017400255** [comment]
While uploading the report:
● Create a directory called “deliverables” in repository.
● Name our milestone report as “M1-Group11”.

**Comment by aysusayin** [comment]
I start preparing the report on Overleaf. Here is the view only link: https://www.overleaf.com/read/xdrmzjqmqbby.  I'll provide edit link to you on our slack channel.
Currently I'm gathering:
● Communication plan
● Requirements and mockups
● Design

**Comment by aysusayin** [comment]
Missing parts: 
- [ ] Road ahead
- [ ] Work done
- [ ] Evaluation of tools

The rest is added to the report.

**Comment by aysusayin** [comment]
Uploaded the first version of the milestone 1 report. We may make necessary changes or additions until 01.04.2019 10.00 am. I am now closing this issue.
