### ISSUE TITLE
Prepare list, status and evaluation of deliverables for Milestone Report 1

### ISSUE THREAD

**Issue by aysusayin** [bounswe/bounswe2019group11#36]

**Comment by mdumandag** [comment]
I listed the deliverables and write an evaluation for them [here](https://github.com/bounswe/bounswe2019group11/wiki/Milestone-Report#evaluation-of-the-status-of-deliverables-and-its-impact-on-the-project-plan). After reviewing it we may close this issue.

**Comment by aysusayin** [comment]
I reviewed the evaluation and now closing this issue.
