### ISSUE TITLE
choose a web framework for the rest api

### ISSUE THREAD

**Issue by mdumandag** [bounswe/bounswe2019group11#49]
We should discuss and choose a web framework for the rest api backend. The most obvious options are 

- Python
  - [Django](https://www.djangoproject.com/)
  - [Flask](http://flask.pocoo.org/)
- Node.js
  - [Express.js](https://expressjs.com/)

I prefer the Express.js since it is easy to use and @ikamaci knows about this framework. I think it is good to have a team member who can guide us in the process. What do you think ?

**Comment by aysusayin** [comment]
I don't have much experience in JavaScript and I'm more familiar with Python. Although having a team member knowing Node.js is a good thing, I think it would be easier to learn how to implement the API in Python. I read some articles on the web and I have decided that I prefer **Django**.

**Comment by MirageOwl** [comment]
I used Flask before so I have a bias towards that, and I feel more comfortable using python, however I tried Express.js and it is easy to use and has good template engine support. Since we have someone experienced with Express.js I think we can use that.

**Comment by hasan-yaman** [comment]
I have experience with neither Node.js nor Express.js. However, I am comfortable using Python so I will select Python side. I glanced Django once in the last year but I don't have any experience with it. Therefore for frameworks, I am okay to use either Django or Flask.

**Comment by semihakgul** [comment]
I am not experienced in any of them. In any cases I will learn new things but being familiar with Python makes me feel learning Python frameworks will be easier and both Django and Flask is OK to me too.

**Comment by semihakgul** [comment]
After our research and discussions, our final decision is to use express.js for the API.
