### ISSUE TITLE
Search other traders platforms on the internet.

### ISSUE THREAD

**Issue by aysusayin** [bounswe/bounswe2019group11#5]
- [x] Metin Dumandağ
- [x] İbrahim Kamacı
- [x] Hasan Yaman
- [x] Burak Enes Çakıcı
- [x] Alkım Ece Toprak
- [x] Cumhur Kılıç
- [x] Alperen Değirmenci
- [x] Aysu Sayın
- [x] Doğa Yüksel
- [x] Bekir Yıldırım
- [x] Semih Akgül

**Comment by cumhurkilic** [comment]
I recommend you look at the Genesis Vision platform.

**Comment by hasan-yaman** [comment]
[Investing](https://www.investing.com)
