### ISSUE TITLE
Create the Stock Indexes API

### ISSUE THREAD

**Issue by alperen-degirmenci-2017400255** [bounswe/bounswe2019group11#53]

**Comment by hasan-yaman** [comment]
We can use [this](https://www.alphavantage.co) website for stock api. It's free and you can easily create an api key for it. However, it has some limitations: we can make maximum 5 requests per min and 500 requests per day. But, if we encounter this case we can easily create new api key.

**Comment by hasan-yaman** [comment]
For the please [check](https://www.alphavantage.co/documentation/). I also strongly recommend using [postman](https://www.getpostman.com) that enables to test our endpoints.
