### ISSUE TITLE
Write executive summary for Milestone 2 

### ISSUE THREAD

**Issue by hasan-yaman** [bounswe/bounswe2019group11#82]

**Comment by aysusayin** [comment]
Editable link for overleaf document: https://www.overleaf.com/1366524959wxtmgwbmmpww

**Comment by alperen-degirmenci-2017400255** [comment]
Updated the **Introduction** part of the Executive Summary. 

And also updated my **Work done** part, please don't forget updating that part.

**Comment by hasan-yaman** [comment]
I started working on **Work Done So Far** part.
