### ISSUE TITLE
Prepare deliverables material for Milestone Report 2

### ISSUE THREAD

**Issue by alperen-degirmenci-2017400255** [bounswe/bounswe2019group11#83]
Add the deliverables so far to the milestone report 2, we can use the old report as a template.
Aysu will share the link and everyone will be updating the latex file.

**Comment by aysusayin** [comment]
Editable link for overleaf document: https://www.overleaf.com/1366524959wxtmgwbmmpww

**Comment by aysusayin** [comment]
I updated the deliverables table. Evaluation of project plan and implementation assignment need to be added.

**Comment by mdumandag** [comment]
added evaluation of project plan and implementation assignment.
