### ISSUE TITLE
Prepare the milestone 2 report and finalize document

### ISSUE THREAD

**Issue by alperen-degirmenci-2017400255** [bounswe/bounswe2019group11#86]
Collect all the input from friends in the group and convert the latex file to PDF

**Comment by aysusayin** [comment]
Editable link for overleaf document: https://www.overleaf.com/1366524959wxtmgwbmmpww

**Comment by aysusayin** [comment]
We should add latest version of project plan, API URL and documentation in addition to first milestone report. We should update the rest with the contributions of our teammates.

**Comment by aysusayin** [comment]
I added current API documentation to the milestone report.
