### ISSUE TITLE
Update Project Plan

### ISSUE THREAD

**Issue by alperen-degirmenci-2017400255** [bounswe/bounswe2019group11#99]
We need a project plan to follow, as we are approaching Milestone 1.
It should look like the Gantt Chart, as we did in 352.

**Comment by MirageOwl** [comment]
![Papel Project Plan 1](https://user-images.githubusercontent.com/13006910/66748363-a9eb1280-ee8f-11e9-827e-c3ac292b2fd3.png)
Closing issue with this updated plan
